# Generated by Django 4.2.6 on 2023-10-24 19:19

from django.db import migrations, models
import django.db.models.deletion
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_management', '0003_alter_greenhouse_crop_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coordinates', mapbox_location_field.models.LocationField(map_attrs={})),
            ],
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse_management.location'),
        ),
        migrations.DeleteModel(
            name='Localization',
        ),
    ]
