# Generated by Django 4.2.6 on 2023-10-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_management', '0003_alter_greenhouse_crop_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('functionality', models.PositiveSmallIntegerField(choices=[(1, 'Urządzenie pasywne'), (2, 'Urządzenie aktywne')], default=1)),
            ],
        ),
    ]
