# Generated by Django 4.2.6 on 2023-10-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_management', '0006_location_alter_greenhouse_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
