# Generated by Django 4.2.6 on 2023-12-30 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_management', '0006_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='greenhouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='greenhouse_management.greenhouse'),
            preserve_default=False,
        ),
    ]
