# Generated by Django 4.2.6 on 2024-01-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_management', '0007_device_greenhouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enviroment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('air_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PAR', models.DecimalField(decimal_places=2, max_digits=5)),
                ('co2_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_moisture_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_salinity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_of_soil_and_plants', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stem_micro_Variability', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
