# Generated by Django 4.2.6 on 2024-01-16 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_management', '0008_enviroment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('air_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('light_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('par', models.DecimalField(decimal_places=2, max_digits=5)),
                ('co2_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_moisture_level', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_salinity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('soil_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_of_soil_and_plants', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stem_micro_Variability', models.DecimalField(decimal_places=2, max_digits=5)),
                ('green_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhouse_management.greenhouse')),
            ],
        ),
        migrations.DeleteModel(
            name='Enviroment',
        ),
    ]
