# Generated by Django 4.2.6 on 2024-01-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse_management', '0009_environment_delete_enviroment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environment',
            old_name='stem_micro_Variability',
            new_name='stem_micro_variability',
        ),
    ]
